using ProjectEulerAlgorithms.Algorithms;

//Function that returns the sum of the multiples of 3 or 5. 
MultiplesOf3and5 sampleOne = new MultiplesOf3and5();
int result = sampleOne.multiplesOf3and5(49);
Console.WriteLine($"The sum of the multiples is: {result}");

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
EvenFibonacciNumbers sampleTwo = new EvenFibonacciNumbers();
result = sampleTwo.FibonacciNumbers(2);
Console.WriteLine($"The sum of the even values in the fibonacci is: {result}");
