using ProjectEulerAlgorithms.Algorithms;

////Function that returns the sum of the multiples of 3 or 5. 
//MultiplesOf3and5 sampleOne = new MultiplesOf3and5();
//int result = sampleOne.multiplesOf3and5(49);
//Console.WriteLine($"The sum of the multiples is: {result}");

////Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//EvenFibonacciNumbers sampleTwo = new EvenFibonacciNumbers();
//result = sampleTwo.FibonacciNumbers(2);
//Console.WriteLine($"The sum of the even values in the fibonacci is: {result}");

////What is the largest prime factor of the given number?
//LargestPrimeFactor sampleTree = new LargestPrimeFactor();
//long res = sampleTree.largestPrimeFactor(600851475143);
//Console.WriteLine($"The largest prime factor is: {res}");

////Find the largest palindrome made from the product of two n-digit numbers.
//LargestPalindromeProduct sampleFour = new LargestPalindromeProduct();
//result = sampleFour.largestPalindromeProduct(4);
//Console.Write($"the largest palindrome is: {result}");

//What is the smallest positive number that is evenly divisible by all of the numbers from 1 to n?
//SmallestMultiple sampleFive = new SmallestMultiple();
//long res = sampleFive.smallestMultiple(20);
//Console.Write($"the smallest positive number that is evenly divisible by all of the numbers from 1 to n is: {res}");

//Find the difference between the sum of the squares of the first n natural numbers and the square of the sum.
//SumSquareDifference sampleSix = new SumSquareDifference();
//long res = sampleSix.sumSquareDifference(100);
//Console.Write($"the difference between the sum ofthe squares and the square of the sum is: {res}");

//What is the nth prime number?
_10001stPrime sampleSeven = new _10001stPrime();
long res = sampleSeven.nthPrime(10001);
Console.Write($"the prime number n is: {res}");