using ProjectEulerAlgorithms.Algorithms;

//Function that returns the sum of the multiples of 3 or 5. 
MultiplesOf3and5 sampleOne = new MultiplesOf3and5();
int result = sampleOne.multiplesOf3and5(49);
Console.WriteLine($"The sum of the multiples is: {result}");

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
EvenFibonacciNumbers sampleTwo = new EvenFibonacciNumbers();
result = sampleTwo.FibonacciNumbers(2);
Console.WriteLine($"The sum of the even values in the fibonacci is: {result}");

//What is the largest prime factor of the given number?
LargestPrimeFactor sampleTree = new LargestPrimeFactor();
long res = sampleTree.largestPrimeFactor(600851475143);
Console.WriteLine($"The largest prime factor is: {res}");

//Find the largest palindrome made from the product of two n-digit numbers.
LargestPalindromeProduct sampleFour = new LargestPalindromeProduct();
result = sampleFour.largestPalindromeProduct(4);
Console.Write(result);

